name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore EDSEditor.sln
      
    - name: Build
      run: dotnet build EDSEditor.sln --configuration ${{ matrix.configuration }} --no-restore
      
    - name: Test
      run: dotnet test EDSEditor.sln --configuration ${{ matrix.configuration }} --no-build --verbosity normal
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CANopenEditor_net8.0_${{ matrix.configuration }}
        path: |
          EDSEditorGUI2\bin\${{ matrix.configuration }}\net8.0\
          libEDSsharp\bin\${{ matrix.configuration }}\net8.0\
